version: '3.1'
services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: usersoy
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
